# Generated by Django 5.1.6 on 2025-05-15 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.IntegerField()),
                ('class_name', models.CharField(max_length=10)),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('dob', models.DateField()),
                ('subject_1_marks', models.IntegerField()),
                ('subject_2_marks', models.IntegerField()),
                ('subject_3_marks', models.IntegerField()),
                ('subject_4_marks', models.IntegerField()),
                ('student_class', models.CharField(max_length=20)),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_paid', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('class_handled', models.CharField(max_length=100)),
                ('total_salary', models.FloatField()),
                ('salary_obtained', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.student')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.teacher')),
            ],
        ),
    ]
