# Generated by Django 5.1.6 on 2025-05-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='roll_number',
            new_name='subject1',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='subject_1_marks',
            new_name='subject2',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='subject_2_marks',
            new_name='subject3',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='subject_3_marks',
            new_name='subject4',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_class',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subject_4_marks',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='class_handled',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salary_obtained',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='total_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=20),
        ),
    ]
